### ISSUE TITLE
Duplicate values in metadata.csv?

### ISSUE THREAD

**Issue by iknoorjobs** [allenai/cord19#3]
Hi
Just a a random question regarding CORD19 data. The column "cord_uid" in metadata.csv is not unique. In the up to date version, 

```
cord19 = pd.read_csv('metadata.csv')

print(cord19.shape)
(322441, 3)

print(cord19['cord_uid'].nunique())
308694
```

Eg. "c4u0gxp5" has 3 rows with different titles. Why is this the case if the id belongs to the same document?

Thanks
Iknoor

**Comment by kyleclo** [comment]
Hi Iknoor, thanks for your interest in CORD19!  Please see the explanation we provide in our FAQ:
https://github.com/allenai/cord19#why-can-the-same-cord_uid-appear-in-multiple-rows

Thanks!

**Comment by iknoorjobs** [comment]
Hi Kyle,

Oh, got it. Thanks

Best,
Iknoor
