### ISSUE TITLE
corpus.pkl

### ISSUE THREAD

**Issue by talkhanz** [allenai/cord19#5]
Can someone clarify what the corpus.pkl file contains? is it a list of words from metadata.csv abstracts or the full text_documents?

**Comment by kyleclo** [comment]
Hey @talkhanz, where are you seeing a corpus.pkl file?  The dataset should be distributed as .csv and .json files.

**Comment by talkhanz** [comment]
It may be in an earlier version of cord 19 I think 2020-03-20 butI am using the latest version now which does not have the file so I am closing the issue. Thanks
