### ISSUE TITLE
Malware warning (trojan) in one of the JSON files after downloading and unzipping the CORD-19 file

### ISSUE THREAD

**Issue by JProvoost** [allenai/cord19#9]
I want to report a malware warning after downloading and unzipping the file "cord-19_2022-06-02.tar.gz" from the site https://github.com/allenai/cord19. 
Last week I downloaded "Last published version (2022-06-02)", "[Download Link] (https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/historical_releases/cord-19_2022-06-02.tar.gz)", "(size: 18.7Gb, md5: c557069e, sha1: dd2c32bc)". 
The file raised two threats "Trojan: **PowerShell/ReverseShell.SA**" and "Trojan: **PowerShell/Piychan.C**" in the file "**345c97e357144264e93dacb9f2b80005b26cb750.json**". 
Could you please check the file for malware and if applicable make a new file available. 
Thanks in advance.

**Comment by kyleclo** [comment]
Hi @JProvoost . That paper is about malware, so naturally it contains some code snippets that look like malware. The file itself is not malware. But I guess one should avoid trying to execute code snippets contained in the JSON file.

https://www.semanticscholar.org/paper/Python-and-Malware%3A-Developing-Stealth-and-Evasive-Koutsokostas-Patsakis/345c97e357144264e93dacb9f2b80005b26cb750
